version: "3"
services:
  main:
    container_name: crowd_work_main
    build:
      context: .
    env_file:
      - ./env/development.env
    ports:
      - 8080:8080
    command: npm run start
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    restart: always
    ports: 
      - 3306:3306
    container_name: crowd_work_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-example}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-crowd_work}
      TZ: Europe/Samara
    volumes:
      - crowd_work:/var/lib/mysql:rw
    
  phpmyadmin:
    image: phpmyadmin
    container_name: crowd_work_phpmyadmin
    restart: always
    ports:
      - 8087:80
    environment:
      - PMA_ARBITRARY=1
  
volumes:
  crowd_work: